sonar.projectKey=nextjs-devops-training
sonar.projectName=nextjs-devops-training
sonar.projectVersion=1.0
# sonar.host.url=http://localhost:9000
sonar.sources=app
sonar.tests=app
sonar.test.inclusions=**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.token=sqa_52d6912191c136a954b8b0517983c090ec18bd1c
