name: my ci pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: |
          cd nextjs-app
          npm install

      - name: Build app
        run: |
          cd nextjs-app
          npm run build

      - name: Start Next.js server
        run: |
          cd nextjs-app
          npm start &
          sleep 10

      - name: Run test
        run: |
          cd nextjs-app
          node app/__tests__/home.test.tsx