name: my ci pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Start app server
        run: |
          npm start &  # Lance le serveur en arrière-plan
          sleep 5      # Attend que le serveur démarre

      - name: Run API test
        run: node app_tests_home.test.tsx